[tool.black]
line-length = 120
target_version = ['py39']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | env
    | \.mypy_cache
    | \.nox
    | \.tox
    | \.venv
    | \.env
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120
skip = '.eggs, .git, .hg, .mypy_cache, .nox, .tox, .venv, .env, env, _build, buck-out, build, dist'
