name: testing

on: push

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install --upgrade python3.9
      - run: sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.9 10
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: make test


